version: "3.8"

services:
  swirl:
    image: node
    working_dir: /usr/app
    command: bash -c "npm install && npm start"
    volumes:
      - ./web/:/usr/app/
    ports:
      - "80:80"
      - "81:81"
    environment:
      - DELIVERY_SERVER_PORT=80
      - WEBSOCKET_SERVER_PORT=81
